// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzgdbfytzcnuenioouck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Z2RiZnl0emNudWVuaW9vdWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjMxMjEsImV4cCI6MjA2NDQ5OTEyMX0.SR9N3XcoHZik5W6DYbeUi1ML6uzFA3hOlnONI_nX7c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);